import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Button from "@/components/Button/Button";
import CardProfile from "@/components/CardProfile/CardProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tabs = [
  { title: "Основная информация", count: 0, childrens: [], href: "/" },
  { title: "Отпуск", count: 0, childrens: [], href: "/vacation" },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-bg-primary"}>
        <div className="max-w-[1494px] mx-auto pb-6" >
          <Header />
          <Button tw="my-2 mx-2 text-text-tertiary" before="/img/chevron-left.svg" transparent>Вернуться к сотрудикам</Button>
          <div className="flex flex-wrap gap-4 ">
            <CardProfile tw="w-full" data={tabs} />
            {/* <PersonalInformation tw="grow h-fit" />
            <EmployeeLoad tw="grow" /> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
